---
title: "Officers_force_field"
author: "YCR"
date: "Sunday, May 22, 2016"
output: html_document
---


```{r setup, include=FALSE}
#token:
token <- "CzFKSqWPpAUEiBdRqMxw"

# path
path <- "C:/blog/gen/"

# term
term <- "edf"
```

```{r, include=TRUE, eval=TRUE, echo=TRUE, warning=FALSE, include=FALSE}
library(Ropencorporate, quietly = T)
library(data.table)
library(DT)
library(stringr)
library(stringi)
library(networkD3, quietly = T, warn.conflicts = F)
```

```{r, include=FALSE}
load(file = paste0(path, "DATA/res_oc_", term, ".rda")) # res.oc
```

```{r, eval = FALSE, include=FALSE}
company.number <- res.oc$oc.dt[, company.number]
jurisdiction.code <- res.oc$oc.dt[, jurisdiction.code]
company.out.l <- get.comp.number(company.number, jurisdiction.code)
```

```{r, echo = F, eval = F, include=FALSE}
# not displayed: save the data
save(company.out.l, file = paste0(path, "DATA/company_result_query_id_", term, ".rda"))
```

```{r, echo = F, include=FALSE}
# not displayed: load the data
load(file = paste0(path, "DATA/company_result_query_id_", term, ".rda")) # company.out.l
```


```{r, include=FALSE}
officers.comp.dt <- company.out.l$officers.comp.dt

# get rid of second name abreviation
officers.comp.dt[, name.clean := gsub("([ ][A-Z][/.])", "", stri_trans_totitle(tolower(name)))]

# Clean officers title
officers.comp.dt[, position := stri_trans_totitle(tolower(position))]
```




```{r, echo = T, eval = T, include = F}
company.id.dt <- company.out.l$company.id.dt

# merge both tables:
comp.officers <- merge(officers.comp.dt, company.id.dt[
, list(jurisdiction.code, company.number, name.company = name)]
, by = c("jurisdiction.code", "company.number"))

# clear position: if less than 20 of a position, it goes into Other
comp.officers[, position2 := ifelse(.N < 20, "Other", position), by = "position"]
comp.officers[, name2 := paste0(name.clean, ", ", position2)]
comp.officers[, jurisdiction.code2 := ifelse(substring(jurisdiction.code, 1, 2) %in% c("us", "ca")
                          , substring(jurisdiction.code, 1, 2), jurisdiction.code)]
comp.officers[, jurisdiction.code3 := ifelse(.N < 5, "Other", jurisdiction.code2), by = "jurisdiction.code2"]
comp.officers[, name.company2 := paste0(name.company, ", ", jurisdiction.code3)]

# nodes:
nodes.c <- unique(c(comp.officers[, name.clean], comp.officers[, name.company2]))
node0 <- data.frame(ID = 0:(length(nodes.c) - 1)
                    , name = nodes.c, size = 25
                    , stringsAsFactors = F)

# nodes with group: one color per jurisdiction and one for officers
nodes.with.group2 <- merge(node0
      , unique(comp.officers[, list(name.company2 
        , group = as.numeric(as.factor(jurisdiction.code3)))])
      , by.x = "name", by.y = "name.company2", all.x = T)

# put a high value for officers for the group and the size
nodes.with.group2$group[is.na(nodes.with.group2$group)] <- 30
nodes.with.group2$size[is.na(nodes.with.group2$group)] <- 50

# sort the table
node2 <- nodes.with.group2[order(nodes.with.group2$ID), ]

# links 
links.init <- merge(
  merge(
    comp.officers[, list(value = .N), by = c("name.clean", "name.company2")]
    , node0, by.x = "name.company2", by.y = "name", all.x = T)
  , node0, by.x = "name.clean", by.y = "name", all.x = T)

links2 <- data.table(links.init[, list(source = ID.x, target = ID.y
                      , value = value)])
```


```{r, fig.height=20, fig.width=15, eval = T, echo = F, include = T}
forceNetwork(Links = links2, Nodes = node2, Source = "source",
             Target = "target", Value = "value", NodeID = "name",
             Group = "group", opacity = 1, zoom = TRUE)
```

