# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true

# Site Settings
locale                   : "en"
title                    : "Data laborer"
title_separator          : "-"
name                     : "Yves Crutain"
description              : "Personnal blog of a data scientist"
url                      : "https://data-laborer.eu"
baseurl                  : ""
repository               : YvesCR/blog
teaser                   : /assets/images/Hausdülmen_--_2009_--_0706.jpg
theme: minimal-mistakes-jekyll
# breadcrumbs            : false # true, false (default)
words_per_minute         : 100
comments:
  provider               : "disqus"
  disqus:
    shortname            : datalaborereu
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : SwiftAMHE
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: 
    - "https://twitter.com/swiftamhe"
    - "https://www.linkedin.com/in/yves-crutain-0b430324"


analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-71940303-1"

# Site Author
author:
  name             : "Yves Crutain"
  avatar           : "/assets/images/0031e3e.jpg"
  bio              : "Data Scientist: Insight harvester, R Addict, python junky AND foodie. My favourite stack: SQL server + R + opencpu"
  location         : "London"
  email            : "yves.crutain@gmail.com"
  uri              : "data-laborer.eu"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  foursquare       :
  github           : "YvesCR"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "yves-crutain-0b430324"
  pinterest        :
  soundcloud       :
  stackoverflow    : "4911229/ycr"
  steam            :
  tumblr           :
  twitter          : "SwiftAMHE"
  vine             :
  weibo            :
  xing             :
  youtube          :


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Europe/Belfast

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
